<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master List - {{ $strand->code }}</title>
    <style>
        @page { margin: 30px 50px; }
        body {
            font-family: 'Courier New', Courier, monospace;
            font-size: 11pt;
            color: #000;
        }

        .header-container { 
            text-align: center; 
            margin-bottom: 20px; 
        }

        .logo { 
            width: 80px; 
            height: auto; 
            margin-bottom: 5px; 
        }

        .school-name { 
            font-size: 16pt; 
            font-weight: bold; 
            text-transform: uppercase; 
        }

        .school-address { 
            font-size: 10pt; 
            margin-top: 5px; 
            text-transform: uppercase; 
        }

        .contact-no { 
            font-size: 10pt; 
            margin-top: 2px; 
        }

        .doc-title { 
            text-align: center; 
            font-weight: bold; 
            text-decoration: underline; 
            margin: 20px 0; 
            font-size: 14pt; 
        }

        .meta-table { 
            width: 100%; 
            margin-bottom: 15px; 
            font-size: 11pt; 
            border-collapse: collapse; 
        }

        .meta-table td { 
            padding: 3px 0; 
            vertical-align: top; 
        }

        .meta-label { 
            font-weight: bold; 
            width: 18%; 
            white-space: nowrap; 
        }

        .meta-val { 
            width: 32%; 
        }

        .students-table { 
            width: 100%; 
            border-collapse: collapse; 
            border: 1px solid #000; 
            font-size: 11pt; 
        }

        .students-table th { 
            border: 1px solid #000; 
            padding: 5px; 
            background: #eee; 
            text-align: center; 
            font-weight: bold; 
        }

        .students-table td { 
            border: 1px solid #000; 
            padding: 4px; 
        }

        .footer { 
            margin-top: 40px; 
            width: 100%; 
            font-size: 10pt; 
        }
    </style>
</head>
<body>
    @php
        $logoData = null;
        try {
            $path = public_path('images/logo.png');
            if (file_exists($path)) {
                $data = file_get_contents($path);
                $logoData = 'data:image/png;base64,' . base64_encode($data);
            }
        } catch (\Exception $e) {}
    @endphp

    <div class="header-container">
        @if($logoData) <img src="{{ $logoData }}" class="logo"> <br> @endif
        <div class="school-name">HOLY FACE OF JESUS LYCEUM OF SAN JOSE INC.</div>
        <div class="school-address">
            BLK 5 LOT 28-34 VALENTINO VILLAGE,<br>
            SAN JOSE, RODRIGUEZ, RIZAL
        </div>
        <div class="contact-no">Contact No.: 09164369291</div>
    </div>

    <div class="doc-title">STRAND OFFICIAL ENROLLMENT LIST</div>

    <table class="meta-table">
        <tr>
            <td class="meta-label">STRAND CODE:</td>
            <td class="meta-val">{{ strtoupper($strand->code) }}</td>
            <td class="meta-label">SCHOOL YEAR:</td>
            <td class="meta-val">{{ $schoolYear ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td class="meta-label">DESCRIPTION:</td>
            <td class="meta-val">{{ strtoupper($strand->description) }}</td>
            <td class="meta-label">SEMESTER:</td>
            <td class="meta-val">{{ strtoupper($semester ?? 'N/A') }}</td>
        </tr>
        <tr>
            <td class="meta-label">TOTAL ENROLLED:</td>
            <td class="meta-val" colspan="3">{{ count($students) }}</td>
        </tr>
    </table>

    <table class="students-table">
        <thead>
            <tr>
                <th width="10%">NO.</th>
                <th width="25%">STUDENT NUMBER</th>
                <th width="25%">LRN</th>
                <th width="40%">FULL NAME (Last, First, Middle)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $index => $s)
                <tr>
                    <td align="center">{{ $index + 1 }}</td>
                    <td align="center">{{ $s->student_number ?? 'N/A' }}</td>
                    <td align="center">{{ $s->lrn }}</td>
                    <td>
                        {{ strtoupper($s->last_name) }}, {{ strtoupper($s->first_name) }} 
                        @if($s->middle_name) {{ strtoupper(substr($s->middle_name, 0, 1)) }}. @endif 
                        {{ strtoupper($s->suffix) }}
                    </td>
                </tr>
            @empty
                <tr><td colspan="4" align="center" style="font-style: italic;">-- NO ENROLLED STUDENTS FOUND --</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by: {{ $printedBy ?? 'System Admin' }} <br>
        Date: {{ now()->format('F d, Y h:i A') }}
    </div>
</body>
</html>